# Generated by Django 5.2.13 on 2026-04-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_mdl', '0006_otpverification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='system_mdl__email_135090_idx',
            old_name='system_mdl__email_2e8591_idx',
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='system_mdl__email_07c7f6_idx',
            old_name='system_mdl__email_9ec2b3_idx',
        ),
    ]
