# Generated by Django 5.2.13 on 2026-04-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_mdl', '0008_otpverification_hardening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
