from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_page, name='login_page'),
    path('chat/', views.chat_page, name='chat_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('api/auth/csrf/', views.csrf_token, name='csrf_token'),
    path('api/auth/signup/request-otp/', views.signup_request_otp, name='signup_request_otp'),
    path('api/auth/signup/verify-otp/', views.signup_verify_otp, name='signup_verify_otp'),
    path('api/auth/signup/', views.signup, name='signup'),
    path('api/auth/reset/request-otp/', views.reset_request_otp, name='reset_request_otp'),
    path('api/auth/reset/verify-otp/', views.reset_verify_otp, name='reset_verify_otp'),
    path('api/auth/login/', views.login_api, name='login_api'),
    path('api/auth/logout/', views.logout_api, name='logout_api'),
    path('api/auth/me/', views.auth_me, name='auth_me'),
    path('api/auth/profile/', views.update_profile, name='update_profile'),
    path('api/auth/change-password/', views.change_password, name='change_password'),
    path('api/dashboard/', views.dashboard, name='dashboard'),
    path('api/cases/', views.my_cases, name='my_cases'),
    path('api/cases/create/', views.create_case, name='create_case'),
    path('api/cases/<int:case_id>/', views.case_detail, name='case_detail'),
    path('api/cases/<int:case_id>/messages/', views.case_messages, name='case_messages'),
    path('api/cases/<int:case_id>/documents/', views.upload_document, name='upload_document'),
    path('api/staff/departments/', views.get_departments, name='get_departments'),
    path('api/staff/departments/<int:department_id>/members/', views.get_staff_by_department, name='get_staff'),
    path('api/staff/cases/', views.assigned_cases, name='assigned_cases'),
    path('api/staff/cases/<int:case_id>/status/', views.update_case, name='update_case'),
    path('api/staff/students/', views.staff_students, name='staff_students'),
    path('api/notifications/', views.notifications, name='notifications'),
    path('api/notifications/<int:notif_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('api/admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('api/admin/users/', views.admin_users, name='admin_users'),
    path('api/admin/users/create/', views.admin_create_user, name='admin_create_user'),
    path('api/admin/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('api/admin/staff-profile/', views.admin_staff_profile, name='admin_staff_profile'),
    path('api/admin/departments/', views.admin_departments, name='admin_departments'),
    path('api/admin/departments/create/', views.admin_create_department, name='admin_create_department'),
    path('api/admin/departments/<int:department_id>/', views.admin_department_detail, name='admin_department_detail'),
    path('api/admin/faculties/', views.admin_faculties, name='admin_faculties'),
    path('api/admin/faculties/create/', views.admin_create_faculty, name='admin_create_faculty'),
    path('api/admin/cases/', views.admin_cases, name='admin_cases'),
    path('api/admin/cases/<int:case_id>/reassign/', views.admin_reassign_case, name='admin_reassign_case'),
    path('api/admin/cases/<int:case_id>/status/', views.admin_force_case_status, name='admin_force_case_status'),
    path('api/admin/notifications/global/', views.send_global_notification, name='send_global_notification'),
    path('api/ask-ai/', views.ask_ai_view, name='ask_ai'),
    path('api/ai/history/', views.ai_chat_history, name='ai_chat_history'),
]
